### ISSUE TITLE
Suggestion: Use OpenAI JSON Mode

### ISSUE THREAD

**Issue by NicHaley** [hasura/docs-assertion-tester#1]
I noticed the OpenAI call isn't using the [OpenAI JSON Mode](https://platform.openai.com/docs/guides/text-generation/json-mode). Adding this should help improve consistency and performance in the result. Nice work on the repo!

**Comment by robertjdominguez** [comment]
I probably should have turned notifications on for this repo, @NicHaley 😅 

You're right! We experimented with it in the beginning and even then had issues with consistency. However, with the updates from last week, I plan on spending some time later this week and doing a patch release 🤙

**Comment by robertjdominguez** [comment]
Or, I'll do it now 😝
